"""
═══════════════════════════════════════════════════════════
MODULE 1 — SMART DATA ENGINE
GearMind AI · Elecon Engineering Works Pvt. Ltd.
═══════════════════════════════════════════════════════════

WHAT THIS FILE DOES:
  Generates realistic synthetic helical gear sensor data.
  Unlike random data, every feature here is CORRELATED —
  just like real gear physics. This means:
    - High load  → temperature rises
    - Low lubrication → vibration spikes
    - High cycles → wear grows exponentially
    - Fault labels are assigned by real engineering thresholds

HOW TO RUN:
  pip install pandas numpy scikit-learn imbalanced-learn
  python generate_data.py

OUTPUT:
  data/helical_gear_dataset.csv  → main dataset
  data/rul_dataset.csv           → for RUL regression model
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import os

# ── Reproducibility ──────────────────────────────────────
np.random.seed(42)
N = 50_000   # total samples — enough for robust ML training

print("🔧 GearMind Data Engine Starting...")
print(f"   Generating {N:,} physics-informed samples...\n")

# ════════════════════════════════════════════════════════
# STEP 1: Generate Base Features with Physical Correlations
# ════════════════════════════════════════════════════════

# Cycles in Use (0 to 100,000) — represents gear age
cycles = np.random.exponential(scale=30_000, size=N).clip(0, 100_000)

# Load (kN) — normally distributed around 50kN safe operating range
load = np.random.normal(loc=50, scale=18, size=N).clip(10, 120)

# Torque (Nm) — correlated with load (more load = more torque)
# Physics: Torque ∝ Load × gear radius
torque = load * 4.2 + np.random.normal(0, 20, N)
torque = torque.clip(50, 600)

# Lubrication Index (0 to 1) — degrades with cycles
# Physics: lubrication degrades over time (exponential decay)
lubrication_decay = np.exp(-cycles / 80_000)
lubrication = (lubrication_decay + np.random.normal(0, 0.08, N)).clip(0.05, 1.0)

# Wear (mm) — grows with cycles and load
# Physics: Archard's wear equation → Wear ∝ Load × Distance / Hardness
wear = (cycles / 50_000) * (load / 60) * np.random.uniform(0.8, 1.2, N)
wear = wear.clip(0, 4.0)

# Temperature (°C) — rises with load AND poor lubrication
# Physics: Heat generated by friction, reduced by good lubrication
base_temp = 65 + (load - 50) * 0.4
lubrication_heat = (1 - lubrication) * 35   # poor lube = more heat
temperature = base_temp + lubrication_heat + np.random.normal(0, 5, N)
temperature = temperature.clip(40, 150)

# Vibration RMS (mm/s) — spikes with wear and poor lubrication
# Physics: Surface pitting and wear cause vibration harmonics
base_vib = 1.5 + wear * 2.8 + (1 - lubrication) * 4.0
load_vib = (load / 80) * 1.5   # high load adds vibration
vibration = base_vib + load_vib + np.random.normal(0, 0.8, N)
vibration = vibration.clip(0.5, 30)

# Efficiency (%) — drops with wear and high temperature
# Physics: Mechanical efficiency loss from friction and heat
efficiency = 97 - wear * 3.5 - (temperature - 65) * 0.08
efficiency = efficiency + np.random.normal(0, 0.5, N)
efficiency = efficiency.clip(70, 99)

print("   ✅ Base features generated with physics correlations")

# ════════════════════════════════════════════════════════
# STEP 2: Assign Fault Labels Based on Engineering Thresholds
# ════════════════════════════════════════════════════════
# These thresholds come from AGMA gear standards
# (American Gear Manufacturers Association)

def assign_fault_label(row):
    """
    Rule-based fault labeling using engineering thresholds.
    
    MAJOR FAULT: Multiple critical parameters exceeded
    MINOR FAULT: One or two parameters in warning zone
    NO FAULT:    All parameters within safe limits
    """
    # Count how many parameters are in critical/warning zones
    critical_flags = 0
    warning_flags = 0

    # Vibration check (safe: <6, warning: 6-10, critical: >10)
    if row['Vibration RMS (mm/s)'] > 10:
        critical_flags += 1
    elif row['Vibration RMS (mm/s)'] > 6:
        warning_flags += 1

    # Temperature check (safe: <85, warning: 85-95, critical: >95)
    if row['Temperature (°C)'] > 95:
        critical_flags += 1
    elif row['Temperature (°C)'] > 85:
        warning_flags += 1

    # Wear check (safe: <0.8, warning: 0.8-1.2, critical: >1.2)
    if row['Wear (mm)'] > 1.2:
        critical_flags += 1
    elif row['Wear (mm)'] > 0.8:
        warning_flags += 1

    # Lubrication check (safe: >0.5, warning: 0.3-0.5, critical: <0.3)
    if row['Lubrication Index'] < 0.3:
        critical_flags += 1
    elif row['Lubrication Index'] < 0.5:
        warning_flags += 1

    # Efficiency check (safe: >93, warning: 88-93, critical: <88)
    if row['Efficiency (%)'] < 88:
        critical_flags += 1
    elif row['Efficiency (%)'] < 93:
        warning_flags += 1

    # Decision logic
    if critical_flags >= 2:
        return 'Major Fault'
    elif critical_flags == 1 or warning_flags >= 2:
        return 'Minor Fault'
    else:
        return 'No Fault'

# Assign fault type (for explainability)
def assign_fault_type(row):
    """Identifies the specific failure mechanism"""
    if row['Fault Label'] == 'No Fault':
        return 'Healthy'
    
    # Pitting: low lubrication + high temperature
    if row['Lubrication Index'] < 0.35 and row['Temperature (°C)'] > 90:
        return 'Surface Pitting'
    
    # Wear fatigue: high cycles + high wear
    elif row['Wear (mm)'] > 1.0 and row['Cycles in Use'] > 60_000:
        return 'Wear Fatigue'
    
    # Overload: high load + high vibration
    elif row['Load (kN)'] > 85 and row['Vibration RMS (mm/s)'] > 7:
        return 'Overload Vibration'
    
    # Thermal: high temperature as primary driver
    elif row['Temperature (°C)'] > 100:
        return 'Thermal Degradation'
    
    else:
        return 'General Wear'

# ════════════════════════════════════════════════════════
# STEP 3: Build the DataFrame
# ════════════════════════════════════════════════════════

df = pd.DataFrame({
    'Load (kN)':             np.round(load, 2),
    'Torque (Nm)':           np.round(torque, 2),
    'Vibration RMS (mm/s)':  np.round(vibration, 3),
    'Temperature (°C)':      np.round(temperature, 2),
    'Wear (mm)':             np.round(wear, 4),
    'Lubrication Index':     np.round(lubrication, 4),
    'Efficiency (%)':        np.round(efficiency, 2),
    'Cycles in Use':         np.round(cycles).astype(int),
})

print("   ✅ Assigning fault labels (engineering thresholds)...")
df['Fault Label'] = df.apply(assign_fault_label, axis=1)
df['Fault Type']  = df.apply(assign_fault_type,  axis=1)

# ════════════════════════════════════════════════════════
# STEP 4: Generate RUL (Remaining Useful Life) Dataset
# ════════════════════════════════════════════════════════
# RUL = how many cycles until the gear fails completely
# Used for the REGRESSION model (second ML task)

def calculate_rul(row):
    """
    Physics-informed RUL calculation.
    Gears degrade faster with: high load, poor lubrication, high wear
    """
    max_cycles = 100_000  # theoretical maximum gear life
    
    # Degradation penalty factors
    load_penalty       = (row['Load (kN)'] / 60) ** 1.5
    lubrication_factor = 2.0 - row['Lubrication Index']   # poor lube = faster death
    wear_factor        = 1.0 + row['Wear (mm)'] * 0.8
    
    # Effective life consumed
    effective_cycles_used = row['Cycles in Use'] * load_penalty * lubrication_factor * wear_factor
    rul = max(0, max_cycles - effective_cycles_used)
    
    # Add realistic noise
    rul = rul + np.random.normal(0, 500)
    return max(0, round(rul))

print("   ✅ Calculating Remaining Useful Life (RUL)...")
df['RUL (cycles)'] = df.apply(calculate_rul, axis=1)

# ════════════════════════════════════════════════════════
# STEP 5: Save Datasets
# ════════════════════════════════════════════════════════

os.makedirs('data', exist_ok=True)

# Main classification dataset
df.to_csv('data/helical_gear_dataset.csv', index=False)

# RUL regression dataset (separate file)
rul_df = df[['Load (kN)', 'Torque (Nm)', 'Vibration RMS (mm/s)',
             'Temperature (°C)', 'Wear (mm)', 'Lubrication Index',
             'Efficiency (%)', 'Cycles in Use', 'RUL (cycles)']].copy()
rul_df.to_csv('data/rul_dataset.csv', index=False)

# ════════════════════════════════════════════════════════
# STEP 6: Print Summary Stats
# ════════════════════════════════════════════════════════

print("\n" + "═"*55)
print("📊 DATASET SUMMARY")
print("═"*55)
print(f"   Total Samples:    {len(df):,}")
print(f"\n   Fault Distribution:")
for label, count in df['Fault Label'].value_counts().items():
    pct = count/len(df)*100
    bar = '█' * int(pct/2)
    print(f"   {label:<15} {count:>6,} ({pct:5.1f}%)  {bar}")

print(f"\n   Fault Types:")
for ftype, count in df['Fault Type'].value_counts().items():
    print(f"   {ftype:<25} {count:>6,}")

print(f"\n   RUL Statistics:")
print(f"   Mean RUL:  {df['RUL (cycles)'].mean():>10,.0f} cycles")
print(f"   Min RUL:   {df['RUL (cycles)'].min():>10,.0f} cycles")
print(f"   Max RUL:   {df['RUL (cycles)'].max():>10,.0f} cycles")

print("\n✅ Files saved:")
print("   data/helical_gear_dataset.csv")
print("   data/rul_dataset.csv")
print("\n🚀 Run next: python models/train_models.py")
